import React from "react";
import { useNavigate } from "react-router-dom";
import { useAnalysis } from "../context/AnalysisContext";

export default function VisualizationPage() {
  const { state } = useAnalysis();
  const navigate = useNavigate();
  const { heatmap, network, results } = state;

  if (!results) {
    return (
      <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>
        <div className="page-header">
          <h2>Visualizations</h2>
          <p>No visualizations yet. Upload documents and run analysis first.</p>
        </div>
        <div className="page-content">
          <button className="btn btn-primary" onClick={() => navigate("/")}>
            ← Go to Upload
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>
      {/* Header */}
      <div className="page-header">
        <h2>Visualizations</h2>
        <p>
          Graphical representations of document similarity relationships.
        </p>
      </div>

      <div className="page-content" style={{ flex: 1, overflowY: "auto" }}>

        {/* ── Heatmap ─────────────────────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>Similarity Heatmap</h3>
            <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
              Generated by seaborn · TF-IDF cosine similarity
            </span>
          </div>
          <div className="panel-body">
            <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 14 }}>
              Each cell shows the cosine similarity score between two documents.
              Darker blue indicates higher similarity. The diagonal (document vs.
              itself) is grayed out since self-similarity is always 1.0.
            </p>
            {heatmap ? (
              <img
                src={`data:image/png;base64,${heatmap}`}
                alt="Document Similarity Matrix Heatmap"
                className="viz-image"
              />
            ) : (
              <div className="empty-state">Heatmap not available.</div>
            )}
          </div>
        </div>

        {/* ── Network Graph ────────────────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>Similarity Network Graph</h3>
            <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
              Generated by networkx · Suspicious pairs only
            </span>
          </div>
          <div className="panel-body">
            <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 14 }}>
              Each node represents a document. Edges connect documents whose
              cosine similarity exceeds the detection threshold (
              {(state.threshold * 100).toFixed(0)}%).
              Red edges indicate very high similarity (≥ 85%); amber edges indicate
              high similarity (75–84%). Edge thickness scales with similarity score.
              Documents with no edges share low similarity (safe).
            </p>
            {network ? (
              <img
                src={`data:image/png;base64,${network}`}
                alt="Document Similarity Network Graph"
                className="viz-image"
              />
            ) : (
              <div className="empty-state">Network graph not available.</div>
            )}
          </div>
        </div>

        {/* ── Document Summary Table ───────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>Document Summary</h3>
          </div>
          <div style={{ overflowX: "auto" }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Document</th>
                  <th>Size (KB)</th>
                  <th>Words</th>
                  <th>Max Similarity</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {results.documents.map((doc, i) => {
                  const meta = state.fileMetadata.find((m) => m.filename === doc) ||
                    results.metadata?.[doc] || {};
                  // Find the highest similarity this doc has with any other doc
                  const rowScores = results.matrix[i].filter((_, j) => j !== i);
                  const maxScore = rowScores.length > 0 ? Math.max(...rowScores) : 0;
                  const isSuspicious = results.suspicious_pairs.some(
                    (p) => p.doc1 === doc || p.doc2 === doc
                  );
                  return (
                    <tr key={doc}>
                      <td style={{ fontFamily: "monospace", fontSize: 12 }}>{doc}</td>
                      <td>{meta.size_kb ?? "—"}</td>
                      <td>{meta.word_count ?? "—"}</td>
                      <td style={{
                        fontWeight: 600,
                        color: maxScore >= 0.75 ? "var(--warn-text)" : "var(--accent)",
                      }}>
                        {(maxScore * 100).toFixed(1)}%
                      </td>
                      <td>
                        {isSuspicious ? (
                          <span className="badge badge-danger">Flagged</span>
                        ) : (
                          <span className="badge badge-ok">Clear</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
}
