import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useAnalysis } from "../context/AnalysisContext";
import { getClusteredNetwork } from "../services/api";

export default function VisualizationPage() {
  const { state } = useAnalysis();
  const navigate = useNavigate();
  const { heatmap, results, vectorSpace } = state;

  // Local state for the interactive clustered network graph
  const [clusterImage, setClusterImage] = useState(null);
  const [isFetchingCluster, setIsFetchingCluster] = useState(false);
  const [clusterThreshold, setClusterThreshold] = useState(state.threshold || 0.75);
  const [hideSingletons, setHideSingletons] = useState(false);

  // Debounce API calls for the slider
  useEffect(() => {
    if (!results) return;
    const fetchCluster = async () => {
      setIsFetchingCluster(true);
      try {
        const res = await getClusteredNetwork(clusterThreshold, hideSingletons);
        setClusterImage(res.data.image);
      } catch (err) {
        console.error("Failed to fetch clustered network:", err);
      }
      setIsFetchingCluster(false);
    };

    const timer = setTimeout(fetchCluster, 500); // 500ms debounce
    return () => clearTimeout(timer);
  }, [results, clusterThreshold, hideSingletons]);

  if (!results) {
    return (
      <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>
        <div className="page-header">
          <h2>Visualizations</h2>
          <p>No visualizations yet. Upload documents and run analysis first.</p>
        </div>
        <div className="page-content">
          <button className="btn btn-primary" onClick={() => navigate("/")}>
            ← Go to Upload
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column" }}>
      {/* Header */}
      <div className="page-header">
        <h2>Visualizations</h2>
        <p>
          Graphical representations of document similarity relationships.
        </p>
      </div>

      <div className="page-content" style={{ flex: 1, overflowY: "auto" }}>

        {/* ── Heatmap ─────────────────────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>Similarity Heatmap</h3>
            <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
              Generated by seaborn · TF-IDF cosine similarity
            </span>
          </div>
          <div className="panel-body">
            <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 14 }}>
              Each cell shows the cosine similarity score between two documents.
              Darker blue indicates higher similarity. The diagonal (document vs.
              itself) is grayed out since self-similarity is always 1.0.
            </p>
            {heatmap ? (
              <img
                src={`data:image/png;base64,${heatmap}`}
                alt="Document Similarity Matrix Heatmap"
                className="viz-image"
              />
            ) : (
              <div className="empty-state">Heatmap not available.</div>
            )}
          </div>
        </div>

        {/* ── PCA Vector Space ─────────────────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>TF-IDF Vector Space (PCA Projection)</h3>
            <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
              Generated by sklearn PCA
            </span>
          </div>
          <div className="panel-body">
            <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 14 }}>
              TF-IDF represents each document as a high-dimensional vector where each
              dimension corresponds to a vocabulary term. PCA (Principal Component Analysis)
              reduces this to 2D while preserving as much variance as possible, enabling
              spatial visualization. Documents plotted close together share similar
              term-weight distributions and will have high cosine similarity scores.
              Red nodes and dashed lines indicate suspicious pairs above the threshold.
            </p>
            {vectorSpace ? (
              <img
                src={`data:image/png;base64,${vectorSpace}`}
                alt="TF-IDF Document Vector Space PCA 2D Projection"
                className="viz-image"
              />
            ) : (
              <div className="empty-state">PCA vector space plot not available.</div>
            )}
          </div>
        </div>

        {/* ── Network Graph ──────────────────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header" style={{ alignItems: "center" }}>
            <div>
              <h3>Document Similarity Clusters</h3>
              <span style={{ fontSize: 11, color: "var(--text-muted)" }}>
                Connected-component community detection
              </span>
            </div>
            
            <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
              {/* Slider */}
              <div className="threshold-row" style={{ margin: 0, padding: 0, border: "none", background: "none" }}>
                <span className="threshold-label" style={{ fontSize: 11 }}>Edge Threshold:</span>
                <input
                  type="range"
                  min="0.6" max="0.9" step="0.01"
                  value={clusterThreshold}
                  onChange={(e) => setClusterThreshold(parseFloat(e.target.value))}
                  className="threshold-slider"
                  style={{ width: 100 }}
                />
                <span className="threshold-value" style={{ fontSize: 11, minWidth: 35 }}>
                  {(clusterThreshold * 100).toFixed(0)}%
                </span>
              </div>
              
              {/* Checkbox */}
              <label style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 11, cursor: "pointer", color: "var(--text-secondary)", fontWeight: 600 }}>
                <input
                  type="checkbox"
                  checked={hideSingletons}
                  onChange={(e) => setHideSingletons(e.target.checked)}
                />
                Hide singletons
              </label>
            </div>
          </div>
          <div className="panel-body">
            <p style={{ fontSize: 12, color: "var(--text-secondary)", marginBottom: 14 }}>
              Documents are automatically grouped into color-coded clusters if their cosine
              similarity exceeds the configured threshold. This exposes groups of highly
              similar assignments (plagiarism rings). Singletons (isolated white nodes)
              share no significant similarity with any other document at this threshold.
            </p>
            {isFetchingCluster && !clusterImage ? (
              <div className="empty-state">Generating cluster visualization...</div>
            ) : clusterImage ? (
              <div style={{ position: "relative" }}>
                <img
                  src={`data:image/png;base64,${clusterImage}`}
                  alt="Clustered Document Similarity Network Graph"
                  className={`viz-image ${isFetchingCluster ? "opacity-50" : ""}`}
                  style={{ transition: "opacity 0.2s" }}
                />
                {isFetchingCluster && (
                  <div style={{ position: "absolute", top: 10, right: 10 }}>
                    <span className="spinner" />
                  </div>
                )}
              </div>
            ) : (
              <div className="empty-state">Clustered network graph not available.</div>
            )}
          </div>
        </div>

        {/* ── Document Summary Table ───────────────────────────────────── */}
        <div className="panel">
          <div className="panel-header">
            <h3>Document Summary</h3>
          </div>
          <div style={{ overflowX: "auto" }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Document</th>
                  <th>Size (KB)</th>
                  <th>Words</th>
                  <th>Max Similarity</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {results.documents.map((doc, i) => {
                  const meta = state.fileMetadata.find((m) => m.filename === doc) ||
                    results.metadata?.[doc] || {};
                  // Find the highest similarity this doc has with any other doc
                  const rowScores = results.matrix[i].filter((_, j) => j !== i);
                  const maxScore = rowScores.length > 0 ? Math.max(...rowScores) : 0;
                  const isSuspicious = results.suspicious_pairs.some(
                    (p) => p.doc1 === doc || p.doc2 === doc
                  );
                  return (
                    <tr key={doc}>
                      <td style={{ fontFamily: "monospace", fontSize: 12 }}>{doc}</td>
                      <td>{meta.size_kb ?? "—"}</td>
                      <td>{meta.word_count ?? "—"}</td>
                      <td style={{
                        fontWeight: 600,
                        color: maxScore >= 0.75 ? "var(--warn-text)" : "var(--accent)",
                      }}>
                        {(maxScore * 100).toFixed(1)}%
                      </td>
                      <td>
                        {isSuspicious ? (
                          <span className="badge badge-danger">Flagged</span>
                        ) : (
                          <span className="badge badge-ok">Clear</span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

      </div>
    </div>
  );
}
